language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: EXw06mHEokM5HZB9bNzSgl/2oI42G2xA+5XpBkuo5vu44yOlROXD5EwYcJTV15Y6HJJJeY3ChfyfZ3132zpLhLa2UuiFHau+jQ+lk1hLeB7r+sCGnJ7Td34BLgHxuuNIK4uXvtWDfOWmrUJnW4wf84jOpzdZHZhWnflbEZ0RCRID9m/vfnm4Gje/Cwwi3jOrEkQW3703triq5eALytTCU262lXn0+tNQq1s/LUV1/Cq5NN2u3ue6yLuwxhDvOJ21KKt6F2rVUp0yhD3TAADZaj3Q/TlFE8xoOllmRkNjXp13UIb/WTR6q3l59wDqD4WC9/JnoTa10+I3NENCn+BGDkL7R08+TxvJrLHo/NB/fdhcZDLRrVoyu/Up1uYk9zsA3e2UDgH5QLeNrFvvs9TkjFJjyiTK60qbh5d4QgrsNplWBPRv2OwKgFlS8HYjvMuYBzYurqPhWzKmRxAPRYimn5kW4l4aPsd4tFwvNzWlCU66vq2cPyZRF5yMPVqujYEYk0MQ1eiKqA6TSdKh5WFk5Yqo2IeXl/D40N/OGAEyQ3or8Zuob/EBcgvrO5yLayIxwiRsuoeyB+ZjYWSStWKkjwvLd/Hmd0BLco8pYGFrcTsmR/IVlnXGWmKmnFVywfz+3nbzGHk+Oqu+mTnzCeWojPqLK+XDeBd81Uf1RVXHhWE=
  on:
    tags: true
    repo: octoblu/node-meshblu-websocket
