language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: FBVoQK5qXvwZ8a317HjMcIGhAfOpsXKlsm7nsYsh8bvphVZE+hingv8Fdbs5yTanRW/91mJETH+STPHUMyuoU2gtkCi2fjYTnMQsL2b2+vzoxTl9/b5g4VIwxlBC6KPzIUCegn4xF61vzoCDXiOGRaOqU+J1UVl/5qG2TGaU7CU8Wo8EdR50i1QL81R1VW1f0hgBRirs/+aoyOjrgOxuSK0QlaIgS/Ad7wjBLVaG7CGQ0XHHEliJoJVv0rrpFr64BhEXS/4oxlmiOs8l2QklidC5eZFrzhSX9aXSQL6n7oDeu7kcdnXuzK7mNrVqgHYnIRTHoEabYtGpVq32uITXcaghDrEWcMuKteLBFhHtPsqhIZizCZBaBmz1ELQYkKOxy5FO4rIUfwB6m/jLHVmDsVSRz51Qt9qsUwuBMrCOK61Ip6SFIIJWbd+Jh4Tj+oVMmWVzFEocF6D1y99RcNBqrX2n93wEylC6x23rvIUzr1ylnhNhBFAlX06ffToqzL7ckmZsTFXI5n5mWZhU4X1F9zZZmu5urdRWKmX1wfdDD+fvNM8UGIaSQ1xeVf9s9m8tAu1S+ROjQW8ObzcdUoyuBZa6sOBaIrRkw6MMJgUtnMgvWJ3mqCe2Xw2f3Nub1r37X5OhEZXggrDP6/dGfgXbk1VvP8Z23I1qD0DrufRDR+I=
  on:
    tags: true
    repo: octoblu/node-meshblu-websocket
